FNT_TITLE     = $9000;
SCR_TITLE     = $9800;
FAD_TITLE     = $9c00;
SCR2_ADDR     = $8000;

RMT_PLAYER    = $8c00;

SPR_ADDR      = $a000;

FNT_STATUS    = $a400;
STATUS_ADDR   = $a800;
GOVER_ADDR    = $a880;
CRATER_ADDR   = $a8f8;

FNT_GAME      = $ac00;

PMG_ADDR      = $B000;

SCREEN_ADDR   = $b800;
SCR_GAME      = SCREEN_ADDR+168;

DL_TITLE      = $bf90;
DL_GAME       = $bfd0;
DL_GAME_ADDR  = DL_GAME+14;
DL_STAT_ADDR  = DL_GAME+33;

RMT_MODUL     = $c000;

//

PTR1 = $50;
PTR2 = $52;
PTR3 = $54;
